#!/bin/bash
#Menu

clear

echo -e "*****************************************************"
echo -e "*         Welcome to AutoscriptVPS Menu             *"                                 
echo -e "*   modefied by: jhelson15 contact: 09496942848     *"
echo -e "*****************************************************"
echo -e "###################### menu #########################"
echo -e "1) Add-User    : Add new user client"
echo -e "2) Trial       : Auto generate trial valid for 1day"
echo -e "3) Delete      : Delete user"
echo -e "4) Userlist    : check client account expiration"
echo -e "*****************************************************"                              
echo -e "*      Please Type [1-4] on Menu: Sample: 1         *"              
echo -e "*****************************************************"
echo -e "-----------------------------------------------------"
echo -e "                   Server Menu                       " 
echo -e "                      OPTION"
echo -e "refresh     : restart service dropbear, webmin"
echo -e "                squid3, openvpn dan ssh"
echo -e "speedtest   : speedtest VPS"
echo -e "info        : System information"
echo -e "about       : info script auto install"
echo -e "reboot      : reboot VPS"
echo -e "exit        : Open thru Putty/Connecbot/"
echo -e "                      JuiceSSH"
echo -e "******************************************************"                              
echo -e "* Please Type OPTION on SERVER MENU: Sample:refresh  *"              
echo -e "******************************************************"
echo -e ""
