#!/bin/bash
#Menu
echo -e "Welcome to AutoscriptVPS Menu"
echo -e "modefied by: jhelson15 contact: 09496942848"
echo -e ""
echo -e ""
echo -e "+Option+    : Description"
echo -e "* menu      : memu Description"
echo -e "* usernew   : create new user client"
echo -e "* trial     : create new trial valid for 1day"
echo -e "* delete    : delete user "
echo -e "* check     : check user login"
echo -e "* status    : check user online status"
echo -e "* member    : check client account"
#echo -e "* refresh   : restart service dropbear, webmin"
#echo -e "              squid3, openvpn dan ssh"
#echo -e "* reboot    : reboot VPS"
#echo -e "* speedtest : speedtest VPS"
#echo -e "* info      : System information"
#echo -e "* about     : info script auto install"
echo -e "* exit      : Open thru Putty/Connecbot/"
echo -e "              JuiceSSH"
echo -e ""
echo -e "Please Type List Under Option: Sample: menu"
echo -e ""
