#!/bin/bash
#Menu
echo -e "Welcome to AutoscriptVPS Menu"
echo -e ""
echo -e "+Option+    : Description"
echo -e "* menu      : memu"
echo -e "* usernew   : create new SSH & OpenVPN"
echo -e "* trial     : create new trial"
echo -e "* delete    : delete user SSH & OpenVPN"
echo -e "* check     : check user login"
echo -e "* member    : check member SSH & OpenVPN"
echo -e "* refresh   : restart service dropbear, webmin"
echo -e "              squid3, openvpn dan ssh"
echo -e "* reboot    : reboot VPS"
echo -e "* speedtest : speedtest VPS"
echo -e "* info      : System information"
echo -e "* about     : info script auto install"
echo -e "* exit      : Open thru Putty/Connecbot/"
echo -e "              JuiceSSH"
echo -e ""
echo -e "Please Type to Option: Sample: menu"
echo -e ""
